# permissions for end users to view kubernetessecretengineroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetessecretenginerole-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetessecretengineroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetessecretengineroles/status
  verbs:
  - get
