---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - approleauthengineroles
  - auditrequestheaders
  - audits
  - authenginemounts
  - awsauthengineclientconfigs
  - awsauthengineidentityconfigs
  - awsauthengineroles
  - awssecretengineconfigs
  - awssecretengineroles
  - azureauthengineconfigs
  - azureauthengineroles
  - azuresecretengineconfigs
  - azuresecretengineroles
  - certauthengineconfigs
  - certauthengineroles
  - consulsecretengineconfigs
  - consulsecretengineroles
  - databasesecretengineconfigs
  - databasesecretengineroles
  - databasesecretenginestaticroles
  - entities
  - entityaliases
  - gcpauthengineconfigs
  - gcpauthengineroles
  - gcpsecretengineconfigs
  - gcpsecretenginerolesets
  - gcpsecretenginestaticaccounts
  - githubsecretengineconfigs
  - githubsecretengineroles
  - groupaliases
  - groups
  - identityoidcassignments
  - identityoidcclients
  - identityoidcproviders
  - identityoidcscopes
  - identitytokenconfigs
  - identitytokenkeys
  - identitytokenroles
  - jwtoidcauthengineconfigs
  - jwtoidcauthengineroles
  - kubernetesauthengineconfigs
  - kubernetesauthengineroles
  - kubernetessecretengineconfigs
  - kubernetessecretengineroles
  - ldapauthengineconfigs
  - ldapauthenginegroups
  - ldapsecretengineconfigs
  - ldapsecretenginedynamicroles
  - ldapsecretenginestaticroles
  - mongodbatlassecretengineconfigs
  - mongodbatlassecretengineroles
  - namespaces
  - nomadsecretengineconfigs
  - nomadsecretengineroles
  - oktaauthengineconfigs
  - oktaauthenginegroups
  - passwordpolicies
  - pkisecretengineconfigs
  - pkisecretengineroles
  - policies
  - quaysecretengineconfigs
  - quaysecretengineroles
  - quaysecretenginestaticroles
  - rabbitmqsecretengineconfigs
  - rabbitmqsecretengineroles
  - randomsecrets
  - secretenginemounts
  - sshsecretengineconfigs
  - sshsecretengineroles
  - terraformcloudsecretengineconfigs
  - terraformcloudsecretengineroles
  - totpsecretenginekeys
  - transitsecretenginekeys
  - vaultsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - approleauthengineroles/finalizers
  - auditrequestheaders/finalizers
  - audits/finalizers
  - authenginemounts/finalizers
  - awsauthengineclientconfigs/finalizers
  - awsauthengineidentityconfigs/finalizers
  - awsauthengineroles/finalizers
  - awssecretengineconfigs/finalizers
  - awssecretengineroles/finalizers
  - azureauthengineconfigs/finalizers
  - azureauthengineroles/finalizers
  - azuresecretengineconfigs/finalizers
  - azuresecretengineroles/finalizers
  - certauthengineconfigs/finalizers
  - certauthengineroles/finalizers
  - consulsecretengineconfigs/finalizers
  - consulsecretengineroles/finalizers
  - databasesecretengineconfigs/finalizers
  - databasesecretengineroles/finalizers
  - databasesecretenginestaticroles/finalizers
  - entities/finalizers
  - entityaliases/finalizers
  - gcpauthengineconfigs/finalizers
  - gcpauthengineroles/finalizers
  - gcpsecretengineconfigs/finalizers
  - gcpsecretenginerolesets/finalizers
  - gcpsecretenginestaticaccounts/finalizers
  - githubsecretengineconfigs/finalizers
  - githubsecretengineroles/finalizers
  - groupaliases/finalizers
  - groups/finalizers
  - identityoidcassignments/finalizers
  - identityoidcclients/finalizers
  - identityoidcproviders/finalizers
  - identityoidcscopes/finalizers
  - identitytokenconfigs/finalizers
  - identitytokenkeys/finalizers
  - identitytokenroles/finalizers
  - jwtoidcauthengineconfigs/finalizers
  - jwtoidcauthengineroles/finalizers
  - kubernetesauthengineconfigs/finalizers
  - kubernetesauthengineroles/finalizers
  - kubernetessecretengineconfigs/finalizers
  - kubernetessecretengineroles/finalizers
  - ldapauthengineconfigs/finalizers
  - ldapauthenginegroups/finalizers
  - ldapsecretengineconfigs/finalizers
  - ldapsecretenginedynamicroles/finalizers
  - ldapsecretenginestaticroles/finalizers
  - mongodbatlassecretengineconfigs/finalizers
  - mongodbatlassecretengineroles/finalizers
  - namespaces/finalizers
  - nomadsecretengineconfigs/finalizers
  - nomadsecretengineroles/finalizers
  - oktaauthengineconfigs/finalizers
  - oktaauthenginegroups/finalizers
  - passwordpolicies/finalizers
  - pkisecretengineconfigs/finalizers
  - pkisecretengineroles/finalizers
  - policies/finalizers
  - quaysecretengineconfigs/finalizers
  - quaysecretengineroles/finalizers
  - quaysecretenginestaticroles/finalizers
  - rabbitmqsecretengineroles/finalizers
  - randomsecrets/finalizers
  - secretenginemounts/finalizers
  - sshsecretengineconfigs/finalizers
  - sshsecretengineroles/finalizers
  - terraformcloudsecretengineconfigs/finalizers
  - terraformcloudsecretengineroles/finalizers
  - totpsecretenginekeys/finalizers
  - transitsecretenginekeys/finalizers
  - vaultsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - approleauthengineroles/status
  - auditrequestheaders/status
  - audits/status
  - authenginemounts/status
  - awsauthengineclientconfigs/status
  - awsauthengineidentityconfigs/status
  - awsauthengineroles/status
  - awssecretengineconfigs/status
  - awssecretengineroles/status
  - azureauthengineconfigs/status
  - azureauthengineroles/status
  - azuresecretengineconfigs/status
  - azuresecretengineroles/status
  - certauthengineconfigs/status
  - certauthengineroles/status
  - consulsecretengineconfigs/status
  - consulsecretengineroles/status
  - databasesecretengineconfigs/status
  - databasesecretengineroles/status
  - databasesecretenginestaticroles/status
  - entities/status
  - entityaliases/status
  - gcpauthengineconfigs/status
  - gcpauthengineroles/status
  - gcpsecretengineconfigs/status
  - gcpsecretenginerolesets/status
  - gcpsecretenginestaticaccounts/status
  - githubsecretengineconfigs/status
  - githubsecretengineroles/status
  - groupaliases/status
  - groups/status
  - identityoidcassignments/status
  - identityoidcclients/status
  - identityoidcproviders/status
  - identityoidcscopes/status
  - identitytokenconfigs/status
  - identitytokenkeys/status
  - identitytokenroles/status
  - jwtoidcauthengineconfigs/status
  - jwtoidcauthengineroles/status
  - kubernetesauthengineconfigs/status
  - kubernetesauthengineroles/status
  - kubernetessecretengineconfigs/status
  - kubernetessecretengineroles/status
  - ldapauthengineconfigs/status
  - ldapauthenginegroups/status
  - ldapsecretengineconfigs/status
  - ldapsecretenginedynamicroles/status
  - ldapsecretenginestaticroles/status
  - mongodbatlassecretengineconfigs/status
  - mongodbatlassecretengineroles/status
  - namespaces/status
  - nomadsecretengineconfigs/status
  - nomadsecretengineroles/status
  - oktaauthengineconfigs/status
  - oktaauthenginegroups/status
  - passwordpolicies/status
  - pkisecretengineconfigs/status
  - pkisecretengineroles/status
  - policies/status
  - quaysecretengineconfigs/status
  - quaysecretengineroles/status
  - quaysecretenginestaticroles/status
  - rabbitmqsecretengineconfigs/status
  - rabbitmqsecretengineroles/status
  - randomsecrets/status
  - secretenginemounts/status
  - sshsecretengineconfigs/status
  - sshsecretengineroles/status
  - terraformcloudsecretengineconfigs/status
  - terraformcloudsecretengineroles/status
  - totpsecretenginekeys/status
  - transitsecretenginekeys/status
  - vaultsecrets/status
  verbs:
  - get
  - patch
  - update
