apiVersion: redhatcop.redhat.io/v1alpha1
kind: IdentityTokenKey
metadata:
  name: identitytokenkey-sample
spec:
  authentication:
    path: kubernetes
    role: policy-admin
  rotationPeriod: "24h"
  verificationTTL: "24h"
  allowedClientIDs:
  - "*"
  algorithm: RS256
