/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"context"
	"encoding/json"
	"reflect"
	"strconv"

	vaultutils "github.com/redhat-cop/vault-config-operator/api/v1alpha1/utils"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// TOTPSecretEngineKeySpec defines the desired state of TOTPSecretEngineKey
type TOTPSecretEngineKeySpec struct {

	// Connection represents the information needed to connect to Vault. This operator uses the standard Vault environment variables to connect to Vault. If you need to override those settings and for example connect to a different Vault instance, you can do with this section of the CR.
	// +kubebuilder:validation:Optional
	Connection *vaultutils.VaultConnection `json:"connection,omitempty"`

	// Authentication is the k8s auth configuration to be used to execute this request
	// +kubebuilder:validation:Required
	Authentication vaultutils.KubeAuthConfiguration `json:"authentication"`

	// Path at which to make the configuration.
	// The final path in Vault will be {[spec.authentication.namespace]}/{spec.path}/keys/{spec.name or metadata.name}.
	// The authentication role must have the following capabilities = [ "create", "read", "update", "delete"] on that path.
	// +kubebuilder:validation:Required
	Path vaultutils.Path `json:"path"`

	TOTPKeyConfig `json:",inline"`

	// The name of the object created in Vault. If this is specified it takes precedence over {metadata.name}
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Pattern:=`[a-z0-9]([-a-z0-9]*[a-z0-9])?`
	Name string `json:"name,omitempty"`
}

// TOTPKeyConfig defines the configuration fields for a TOTP key in Vault.
type TOTPKeyConfig struct {

	// Generate specifies if a key should be generated by Vault (true) or imported (false).
	// When true, Vault generates the secret key internally.
	// When false, provide key or url to import an existing TOTP secret.
	// +kubebuilder:validation:Optional
	Generate bool `json:"generate,omitempty"`

	// Exported controls whether a QR code and url are returned when generating a key.
	// Only used when generate is true.
	// +kubebuilder:validation:Optional
	Exported *bool `json:"exported,omitempty"`

	// KeySize specifies the size in bytes of the Vault-generated key.
	// Only used when generate is true.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Minimum=0
	KeySize int `json:"keySize,omitempty"`

	// URL specifies a TOTP key URL (otpauth:// format) for importing.
	// Only used when generate is false.
	// +kubebuilder:validation:Optional
	URL string `json:"url,omitempty"`

	// Key specifies the Base32-encoded root key for importing.
	// Only used when generate is false.
	// +kubebuilder:validation:Optional
	Key string `json:"key,omitempty"`

	// Issuer specifies the name of the key's issuing organization.
	// +kubebuilder:validation:Optional
	Issuer string `json:"issuer,omitempty"`

	// AccountName specifies the name of the account associated with the key.
	// +kubebuilder:validation:Optional
	AccountName string `json:"accountName,omitempty"`

	// Period specifies the length of time in seconds used to generate a counter for the TOTP code.
	// +kubebuilder:validation:Optional
	// +kubebuilder:default=30
	// +kubebuilder:validation:Minimum=1
	Period int `json:"period"`

	// Algorithm specifies the hashing algorithm used to generate the TOTP code.
	// +kubebuilder:validation:Optional
	// +kubebuilder:default="SHA1"
	// +kubebuilder:validation:Enum={"SHA1","SHA256","SHA512"}
	Algorithm string `json:"algorithm"`

	// Digits specifies the number of digits in the generated TOTP code (6 or 8).
	// +kubebuilder:validation:Optional
	// +kubebuilder:default=6
	// +kubebuilder:validation:Enum={6,8}
	Digits int `json:"digits"`

	// Skew specifies the number of delay periods allowed when validating a TOTP code (0 or 1).
	// Only used when generate is true.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=1
	Skew int `json:"skew,omitempty"`

	// QRSize specifies the pixel size of the square QR code.
	// Only used when generate is true and exported is true. 0 means no QR code.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Minimum=0
	QRSize int `json:"qrSize,omitempty"`
}

// TOTPSecretEngineKeyStatus defines the observed state of TOTPSecretEngineKey
type TOTPSecretEngineKeyStatus struct {
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status

// TOTPSecretEngineKey is the Schema for the totpsecretenginekeys API
type TOTPSecretEngineKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   TOTPSecretEngineKeySpec   `json:"spec,omitempty"`
	Status TOTPSecretEngineKeyStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// TOTPSecretEngineKeyList contains a list of TOTPSecretEngineKey
type TOTPSecretEngineKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TOTPSecretEngineKey `json:"items"`
}

var _ vaultutils.ConditionsAware = &TOTPSecretEngineKey{}

func (d *TOTPSecretEngineKey) GetVaultConnection() *vaultutils.VaultConnection {
	return d.Spec.Connection
}

func (m *TOTPSecretEngineKey) GetConditions() []metav1.Condition {
	return m.Status.Conditions
}

func (m *TOTPSecretEngineKey) SetConditions(conditions []metav1.Condition) {
	m.Status.Conditions = conditions
}

func (d *TOTPSecretEngineKey) IsDeletable() bool {
	return true
}

func init() {
	SchemeBuilder.Register(&TOTPSecretEngineKey{}, &TOTPSecretEngineKeyList{})
}

var _ vaultutils.VaultObject = &TOTPSecretEngineKey{}

func (d *TOTPSecretEngineKey) GetPath() string {
	name := d.Name
	if d.Spec.Name != "" {
		name = d.Spec.Name
	}
	return vaultutils.CleansePath(string(d.Spec.Path) + "/" + "keys" + "/" + name)
}

func (d *TOTPSecretEngineKey) GetPayload() map[string]any {
	return d.Spec.TOTPKeyConfig.toMap()
}

func (d *TOTPSecretEngineKey) IsEquivalentToDesiredState(payload map[string]any) bool {
	desiredState := d.Spec.TOTPKeyConfig.readVisibleMap()
	return reflect.DeepEqual(desiredState, filterPayloadToDesiredKeys(desiredState, payload))
}

func (d *TOTPSecretEngineKey) IsInitialized() bool {
	return true
}

func (d *TOTPSecretEngineKey) PrepareInternalValues(context context.Context, object client.Object) error {
	return nil
}

func (d *TOTPSecretEngineKey) PrepareTLSConfig(context context.Context, object client.Object) error {
	return nil
}

func (d *TOTPSecretEngineKey) IsValid() (bool, error) {
	return true, nil
}

func (d *TOTPSecretEngineKey) GetKubeAuthConfiguration() *vaultutils.KubeAuthConfiguration {
	return &d.Spec.Authentication
}

func (c *TOTPKeyConfig) algorithmOrDefault() string {
	if c.Algorithm == "" {
		return "SHA1"
	}
	return c.Algorithm
}

func (c *TOTPKeyConfig) digitsOrDefault() int {
	if c.Digits == 0 {
		return 6
	}
	return c.Digits
}

func (c *TOTPKeyConfig) periodOrDefault() int {
	if c.Period == 0 {
		return 30
	}
	return c.Period
}

func (c *TOTPKeyConfig) keySizeOrDefault() int {
	if c.KeySize == 0 {
		return 20
	}
	return c.KeySize
}

func (c *TOTPKeyConfig) qrSizeOrDefault() int {
	if c.QRSize == 0 {
		return 200
	}
	return c.QRSize
}

// readVisibleMap returns only the fields Vault returns on GET {path}/keys/{name}.
// Vault returns exactly: account_name, algorithm, digits, issuer, period.
func (c *TOTPKeyConfig) readVisibleMap() map[string]any {
	payload := map[string]any{}
	payload["issuer"] = c.Issuer
	payload["account_name"] = c.AccountName
	payload["algorithm"] = c.algorithmOrDefault()
	payload["digits"] = json.Number(strconv.Itoa(c.digitsOrDefault()))
	payload["period"] = json.Number(strconv.Itoa(c.periodOrDefault()))
	return payload
}

// toMap returns the full write payload for POST {path}/keys/{name}.
func (c *TOTPKeyConfig) toMap() map[string]any {
	payload := map[string]any{}
	payload["generate"] = c.Generate
	payload["issuer"] = c.Issuer
	payload["account_name"] = c.AccountName
	payload["algorithm"] = c.algorithmOrDefault()
	payload["digits"] = json.Number(strconv.Itoa(c.digitsOrDefault()))
	payload["period"] = json.Number(strconv.Itoa(c.periodOrDefault()))
	if c.Generate {
		exported := true
		if c.Exported != nil {
			exported = *c.Exported
		}
		payload["exported"] = exported
		payload["key_size"] = json.Number(strconv.Itoa(c.keySizeOrDefault()))
		payload["skew"] = json.Number(strconv.Itoa(c.Skew))
		payload["qr_size"] = json.Number(strconv.Itoa(c.qrSizeOrDefault()))
	} else {
		if c.Key != "" {
			payload["key"] = c.Key
		}
		if c.URL != "" {
			payload["url"] = c.URL
		}
	}
	return payload
}
