# Adds namespace to all resources.
namespace: release-namespace

resources:
- ../local-development/tilt

replacements:
- source:
    kind: Service
    version: v1
    name: controller-manager-metrics-service
    fieldPath: metadata.namespace
  targets:
  - select:
      kind: ServiceMonitor
      name: controller-manager-metrics-monitor
    fieldPaths:
    - spec.endpoints.0.tlsConfig.serverName
    options:
      delimiter: "."
      index: 1

patches:
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: MutatingWebhookConfiguration
    name: vault-config-operator-mutating-webhook-configuration
  path: ./cert-manager-ca-injection.yaml
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
    name: vault-config-operator-validating-webhook-configuration
  path: ./cert-manager-ca-injection.yaml