name: pull request
on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      kubectl-wait-timeout:
        description: "kubectl wait timeout used for integration and helmchart-test targets in the Makefile (e.g. 5m)"
        required: false
        default: "20m"

jobs:
  shared-operator-workflow:
    name: shared-operator-workflow
    uses: trevorbox/github-workflows-operators/.github/workflows/pr-operator.yml@44fcea4bf1c011c5a64fa7f5b887390c9f9dd2a6
    with: 
      RUN_UNIT_TESTS: true
      RUN_INTEGRATION_TESTS: true
      RUN_HELMCHART_TEST: true
      GO_VERSION: ~1.22
      OPERATOR_SDK_VERSION: v1.31.0
      KUBECTL_WAIT_TIMEOUT: ${{ github.event.inputs['kubectl-wait-timeout'] != '' && github.event.inputs['kubectl-wait-timeout'] || vars.KUBECTL_WAIT_TIMEOUT != '' && vars.KUBECTL_WAIT_TIMEOUT || '20m' }}
